### PR TITLE
Fix compatibility with Ruby 2.7

### LINKED ISSUE #206: Puppet 7: undefined method `load_file' for JSON:Module
A Ruby 2.7 compatibility issue was introduced in 46b97a7.  Testing using Puppet 7 now results in the following error:
```
Failure/Error: require 'rspec-puppet-facts'
NoMethodError:
  undefined method `load_file' for JSON:Module
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-facts-5.3.0/lib/rspec-puppet-facts.rb:400:in `facter_version_for_puppet_version'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-facts-5.3.0/lib/rspec-puppet-facts.rb:419:in `block in <top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-facts-5.3.0/lib/rspec-puppet-facts.rb:418:in `<top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-5.0.0/lib/rspec-puppet/monkey_patches.rb:399:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-5.0.0/lib/rspec-puppet/monkey_patches.rb:399:in `require'
# ./spec/spec_helper.rb:8:in `<top (required)>'
```

### PR DESCRIPTION
**Pull request by silug**
Closes #206

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
We do test on Ruby 2.7 so I wonder why this wasn't caught

**Comment by ekohl** [comment]
I still don't get why this didn't show in CI. It's true the method was only added in Ruby 3.0 but why was CI with Ruby 2.7 green? Did the gem silently get updated?
