### ISSUE TITLE
Puppet 7: undefined method `load_file' for JSON:Module

### ISSUE THREAD

**Issue by silug** [voxpupuli/rspec-puppet-facts#206]
A Ruby 2.7 compatibility issue was introduced in 46b97a7.  Testing using Puppet 7 now results in the following error:
```
Failure/Error: require 'rspec-puppet-facts'
NoMethodError:
  undefined method `load_file' for JSON:Module
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-facts-5.3.0/lib/rspec-puppet-facts.rb:400:in `facter_version_for_puppet_version'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-facts-5.3.0/lib/rspec-puppet-facts.rb:419:in `block in <top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-facts-5.3.0/lib/rspec-puppet-facts.rb:418:in `<top (required)>'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-5.0.0/lib/rspec-puppet/monkey_patches.rb:399:in `require'
# ./vendor/bundle/ruby/2.7.0/gems/rspec-puppet-5.0.0/lib/rspec-puppet/monkey_patches.rb:399:in `require'
# ./spec/spec_helper.rb:8:in `<top (required)>'
```

**Comment by bastelfreak** [comment]
Ah derp. Are you able to provide a patch for this? Or a test to reproduce it?
